//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kitapcitakipsistemi.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kitapcitakipsistemi.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ürün Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s01 {
            get {
                return ResourceManager.GetString("s01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satış Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s02 {
            get {
                return ResourceManager.GetString("s02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Ekle-Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s03 {
            get {
                return ResourceManager.GetString("s03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s04 {
            get {
                return ResourceManager.GetString("s04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s05 {
            get {
                return ResourceManager.GetString("s05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s06 {
            get {
                return ResourceManager.GetString("s06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s07 {
            get {
                return ResourceManager.GetString("s07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s08 {
            get {
                return ResourceManager.GetString("s08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s09 {
            get {
                return ResourceManager.GetString("s09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s10 {
            get {
                return ResourceManager.GetString("s10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TC benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s11 {
            get {
                return ResourceManager.GetString("s11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s12 {
            get {
                return ResourceManager.GetString("s12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s13 {
            get {
                return ResourceManager.GetString("s13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyad  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s14 {
            get {
                return ResourceManager.GetString("s14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s15 {
            get {
                return ResourceManager.GetString("s15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s16 {
            get {
                return ResourceManager.GetString("s16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adres benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s17 {
            get {
                return ResourceManager.GetString("s17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s18 {
            get {
                return ResourceManager.GetString("s18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kapat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s19 {
            get {
                return ResourceManager.GetString("s19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s20 {
            get {
                return ResourceManager.GetString("s20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Ekleme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s21 {
            get {
                return ResourceManager.GetString("s21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Listeleme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s22 {
            get {
                return ResourceManager.GetString("s22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satiş Listeleme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s23 {
            get {
                return ResourceManager.GetString("s23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satış İptal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s24 {
            get {
                return ResourceManager.GetString("s24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satış Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s25 {
            get {
                return ResourceManager.GetString("s25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam Fiyatı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s26 {
            get {
                return ResourceManager.GetString("s26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Barkod No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s27 {
            get {
                return ResourceManager.GetString("s27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s28 {
            get {
                return ResourceManager.GetString("s28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s29 {
            get {
                return ResourceManager.GetString("s29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yayın Evi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s30 {
            get {
                return ResourceManager.GetString("s30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mikarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s31 {
            get {
                return ResourceManager.GetString("s31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satış Fiyatı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s32 {
            get {
                return ResourceManager.GetString("s32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Isbn No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s33 {
            get {
                return ResourceManager.GetString("s33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sayfa Sayısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s34 {
            get {
                return ResourceManager.GetString("s34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Raf Numarası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s35 {
            get {
                return ResourceManager.GetString("s35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yazar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s36 {
            get {
                return ResourceManager.GetString("s36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRÜN EKLEME benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s37 {
            get {
                return ResourceManager.GetString("s37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arşiv benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s38 {
            get {
                return ResourceManager.GetString("s38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s39 {
            get {
                return ResourceManager.GetString("s39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s40 {
            get {
                return ResourceManager.GetString("s40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genel Toplam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s41 {
            get {
                return ResourceManager.GetString("s41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satış Fiyatı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s42 {
            get {
                return ResourceManager.GetString("s42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam Fiyatı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s43 {
            get {
                return ResourceManager.GetString("s43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Türkce benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s44 {
            get {
                return ResourceManager.GetString("s44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arşiv benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s45 {
            get {
                return ResourceManager.GetString("s45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s46 {
            get {
                return ResourceManager.GetString("s46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s47 {
            get {
                return ResourceManager.GetString("s47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüm Zamanların Kazancı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s48 {
            get {
                return ResourceManager.GetString("s48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kapat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s49 {
            get {
                return ResourceManager.GetString("s49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TC Ara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s50 {
            get {
                return ResourceManager.GetString("s50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Ürün benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s51 {
            get {
                return ResourceManager.GetString("s51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Var Olan Ürün benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s52 {
            get {
                return ResourceManager.GetString("s52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Barkod No ya göre ara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s53 {
            get {
                return ResourceManager.GetString("s53", resourceCulture);
            }
        }
    }
}
